export enum ValidServices {
  Global = 'global',
  Lists = 'lists',
  Security = 'security',
  Users = 'users',
  Assessments = 'assessments',
  Analytics = 'analytics',
  RhAnalytics = 'rh-analytics',
  Skills = 'skills',
  Pulses = 'pulses',
  Sections = 'sections',
  Questions = 'questions',
  Choices = 'choices',
  Answers = 'answers',
  Dimensions = 'dimensions',
  Organization = 'organization',
  Events = 'events',
  Moodle = 'moodle',
  Feedback = 'feedback',
  Audits = 'audits',
  Organizations = 'organizations',
  Levels = 'levels',
  Reports = 'reports',
  Profiles = 'profiles',
}
